#!/bin/sh

. ${srcdir:?}/build/build.sh

debug "$@"

echo "cc  $2"

CPPFLAGS="-I$srcdir"

if [ -z "$M_CPPFLAGS" ]; then
    target_dir=$(dir "$target")
    M_CPPFLAGS="-I$srcdir/$target_dir -I$srcdir/$target_dir/include"
fi

#src="$(basename "$2" .o).c"
#src="${2%.*}.c"
src="$(ext $2 c)"

gup -u "$srcdir/$src"

gcc "$CPPFLAGS" $M_CPPFLAGS -c -o "$output" "$srcdir/$src"
