#!/usr/bin/env python

import sys

import mk_build
from mk_build import *

output = sys.argv[1]
target = sys.argv[2]

print(f'output={output}')
print(f'target={target}')

print(f'o-asm  {target}')

m_asm_ppflags = mk_build.environ('M_ASM_PPFLAGS', True)
deps = mk_build.environ('DEPS', True)

if deps != '':
    deps = deps.split()
    gup(deps)

source = path(top_source_dir(), path(target).with_suffix('.asm'))

target_source_dir = path_dir(source)

args = ['nasm', '-f', 'elf32', '-g', '-w+error', '-i', target_source_dir,
    m_asm_ppflags, '-o', output, source]

gup(source)

result = run(args)

sys.exit(result.returncode)
