[project]
name = "mk_build"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "tomlkit"
]

[project.optional-dependencies]
test = [
    "coverage",
    "flake8",
    "mypy",
    "pytest"
]

[project.scripts]
configure = "mk_build.configure:main"

[tool.coverage.run]
source = [ "mk_build" ]

[tool.mypy]
packages = [ "mk_build", "test" ]
strict = true

[[tool.mypy.overrides]]
module = [
    "mk_build",
    "mk_build.config",
    "mk_build.configure",
    "mk_build.build.*",
    "mk_build.gup.*",
    "mk_build.log",
    "mk_build.util",
    "mk_build.util.io",
    "mk_build.validate",
    "test.test_build",
    "test.test_gup",
    "test.test_targets",
]
disable_error_code = [
    "attr-defined",
    "comparison-overlap",
    "no-any-return",
    "type-arg"
]
disallow_untyped_calls = false
check_untyped_defs = false
disallow_untyped_defs = false

[tool.pytest.ini_options]
testpaths = [ "test" ]
