[project]
name = "mk_build"
version = "0.0.1"
requires-python = ">=3.10"

dependencies = [
    "tomlkit"
]

[project.optional-dependencies]
test = [
    "coverage",
    "flake8",
    "mypy",
    "types-peewee",
    "pytest"
]

[project.scripts]
configure = "mk_build.configure:main"

#[project.entry-points."entry"]
#mkdash1 = "dashboard.dashboard:main"

[tool.coverage.run]
source = [ "mk_build" ]

[tool.mypy]
explicit_package_bases = true
packages = [ "mk_build", "test" ]

[tool.pytest.ini_options]
testpaths = [ "test" ]
